### ISSUE TITLE
build.sh script fails on macos

### ISSUE THREAD

**Issue by samallman87** [BugelNiels/nitro#73]
following the instructions given in the docs (https://bugelniels.github.io/nitro/df/d06/md_docs_INSTALL.html)- after navigating into the scripts folder and then running 'sh build.sh', the script quickly fails and shows this error:

CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindOpenMP.cmake:577 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.

likewise, when instead trying to build manually - after creating and moving into the build dir, the same error presents after running "cmake -DCMAKE_BUILD_TYPE=Release .."

I'm on macOS 13.4 ventura and have installed all dependencies via brew as instructed in the docs

**Comment by BugelNiels** [comment]
Thanks for letting me know! I'll try to have this fixed for the next version which should be out sometime this week.
In the meantime, what is your CMake version? Also, could you try running `brew install libomp` and see if that changes anything?

**Comment by BugelNiels** [comment]
Could you check whether the latest version works for you?

The GitHub permission denied issue is mostly likely caused by the fact that you don't have an ssh key setup. In the latest version, you should not have this issue anymore (see updated install instructions)

**Comment by samallman87** [comment]
this is the output when following the updated install instructions

❯ bash build.sh
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapOpenGL: TRUE
-- Found WrapVulkanHeaders: /usr/local/include
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenCV: /usr/local/Cellar/opencv/4.8.0_1 (found version "4.8.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_CXX_FOUND)
CMake Error at external/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /Users/samallman1/Documents/GitHub/nitro/external/nodeeditor

  does not contain a CMakeLists.txt file.


CMake Error at external/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /Users/samallman1/Documents/GitHub/nitro/external/flip

  does not contain a CMakeLists.txt file.


CMake Error at external/CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /Users/samallman1/Documents/GitHub/nitro/external/qt-value-slider

  does not contain a CMakeLists.txt file.


OpenMP was not found. Compiling without OpenMP support.
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/lib/libz.tbd (found version "1.2.11")
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.


also, here's the output when cloning into the repo. i added an ssh key and get the same output whether i'm cloning via https or ssh

Cloning into 'nitro'...
remote: Enumerating objects: 15155, done.
remote: Counting objects: 100% (6643/6643), done.
remote: Compressing objects: 100% (3215/3215), done.
remote: Total 15155 (delta 3416), reused 5926 (delta 2952), pack-reused 8512
Receiving objects: 100% (15155/15155), 100.43 MiB | 12.14 MiB/s, done.
Resolving deltas: 100% (8492/8492), done.
Updating files: 100% (319/319), done.
Submodule 'external/doxygen-awesome-css' (https://github.com/jothepro/doxygen-awesome-css.git) registered for path 'external/doxygen-awesome-css'
Submodule 'external/flip' (https://github.com:NVlabs/flip.git) registered for path 'external/flip'
Submodule 'external/nodeeditor' (https://github.com:paceholder/nodeeditor.git) registered for path 'external/nodeeditor'
Submodule 'external/qt-value-slider' (https://github.com:BugelNiels/qt-value-slider.git) registered for path 'external/qt-value-slider'
Cloning into '/Users/samallman1/Documents/GitHub/nitro/external/doxygen-awesome-css'...
remote: Enumerating objects: 2275, done.
remote: Counting objects: 100% (654/654), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 2275 (delta 476), reused 622 (delta 456), pack-reused 1621
Receiving objects: 100% (2275/2275), 8.11 MiB | 10.14 MiB/s, done.
Resolving deltas: 100% (1670/1670), done.
Cloning into '/Users/samallman1/Documents/GitHub/nitro/external/flip'...
fatal: unable to access 'https://github.com:NVlabs/flip.git/': URL rejected: Port number was not a decimal number between 0 and 65535
fatal: clone of 'https://github.com:NVlabs/flip.git' into submodule path '/Users/samallman1/Documents/GitHub/nitro/external/flip' failed
Failed to clone 'external/flip'. Retry scheduled
Cloning into '/Users/samallman1/Documents/GitHub/nitro/external/nodeeditor'...
fatal: unable to access 'https://github.com:paceholder/nodeeditor.git/': URL rejected: Port number was not a decimal number between 0 and 65535
fatal: clone of 'https://github.com:paceholder/nodeeditor.git' into submodule path '/Users/samallman1/Documents/GitHub/nitro/external/nodeeditor' failed
Failed to clone 'external/nodeeditor'. Retry scheduled
Cloning into '/Users/samallman1/Documents/GitHub/nitro/external/qt-value-slider'...
fatal: unable to access 'https://github.com:BugelNiels/qt-value-slider.git/': URL rejected: Port number was not a decimal number between 0 and 65535
fatal: clone of 'https://github.com:BugelNiels/qt-value-slider.git' into submodule path '/Users/samallman1/Documents/GitHub/nitro/external/qt-value-slider' failed
Failed to clone 'external/qt-value-slider'. Retry scheduled
Cloning into '/Users/samallman1/Documents/GitHub/nitro/external/flip'...
fatal: unable to access 'https://github.com:NVlabs/flip.git/': URL rejected: Port number was not a decimal number between 0 and 65535
fatal: clone of 'https://github.com:NVlabs/flip.git' into submodule path '/Users/samallman1/Documents/GitHub/nitro/external/flip' failed
Failed to clone 'external/flip' a second time, aborting

**Comment by BugelNiels** [comment]
It seems there was a slight mistake in the configuration of the git submodules. That should be fixed now. 
Make sure to clone using `--recurse-submodules` flag to ensure that the submodules are correctly cloned:
```shell
git clone --recurse-submodules https://github.com/BugelNiels/nitro.git
````

**Comment by samallman87** [comment]
it worked! thanks so much for all your help
